name: custom_binding
version: 0.0.1
author: Man Hoang <jolleekin@outlook.com>
description: A custom binding syntax built on top of [polymer] that supports transformers.
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  intl: any
  polymer: ^1.0.0-rc.2
dev_dependencies:
  browser: ^0.10.0
  reflectable: ^0.3.1
  web_components: ^0.12.0
transformers:
- web_components:
    entry_points: test/index.html
- reflectable:
    entry_points: test/index.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
